version: '3.8'

services:
  web:
    build: .
    container_name: hotel_audio_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./db:/app/db
      - ./public:/app/public
    restart: unless-stopped